spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ddsermo?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    suffix: .html
    cache: false
    encoding: UTF-8
    check-template: true
    prefix: classpath:/templates/
server:
  port: 8888
  context-path: /ksc
excludeSuffixs: /login,/register

login: /ksc/login